### ISSUE TITLE
To-do list for v2.0

### ISSUE THREAD

**Issue by bbrk24** [bbrk24/lexifer-ts#1]
These are changes that would be nice to have, but require a major version update.

- [x] Drop support for Node v12, as it reaches end of life soon (2022-04-30)
- [ ] Change how the main function handles errors and warnings
  - [ ] Throw errors instead of passing them to a callback
  - [ ] Recoverable errors/warnings: ??
  - [x] Upgrade TypeScript and typescript-eslint -- Done in 66f11596dec50e10edb4d3521d87dee49f323641
- [ ] Move `genWords` into the HTML, rather than including it in the package
- [x] Upgrade browser requirement to ES2018

**Comment by Solomon1732** [comment]
Is this still worked on? I see the repo has not been touched for a year.

**Comment by bbrk24** [comment]
Nominally, I’m still maintaining it. I lost a lot of motivation when I realized that one of the features I wanted for 1.3 would require a significant internal rewrite of something I had just refactored in 1.2, so I haven’t made any progress on new features, but I will fix bugs in 1.2 if they’re reported.

**Comment by nekoniyah** [comment]
You can do something, like, mutation where a sound can have multiple spelling like "o", "au", "eau" in French  the three are pronounced /o/

**Comment by Gravy59** [comment]
Hi there, I would like to propose a possible build system change since it would require major/breaking changes anyway:
- Replace Terser with [Vite](https://vitejs.dev/guide/why), which handles bundling, minification, etc. and is much faster

This is, of course, a non-issue and has no impact on the end product, but is a quality-of-life change. Thanks!

**Comment by Neonnaut** [comment]
It would be great to add to your "Change how the main function handles errors and warnings":
- Show which line of the file the error was on
- ~~Having no words: or categories: directive throws error "failed to choose options from '' ". This would be better as something like "error: no words: or categories: directive"~~ Oops my mistake, it already does. I was thinking of the Python version.

**Comment by Neonnaut** [comment]
For the... web app, the generate function would really benefit using webworker(s) https://macarthur.me/posts/use-web-workers-for-your-event-listeners/

**Comment by Neonnaut** [comment]
The web app could benefit from using a web worker for generating words. I've had great success implementing it for myself.
